number1 = 10
number2 = 5
sum = number1 + number2
sub = number1 - number2
multiply = number1*number2
div = number1/number2
print("the sum of 10 + 5 =" +str (sum))
print("the sub of 10 - 5 =" + str (sub))
print("the multiplication of 10 * 5 =" + str (multiply))
print("the division of 10/5 =" + str(div))
